In [1]:
import tensorflow as tf

In [2]:
# Predicting exam score
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
# multi variable
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
# predicting target
Y = tf.placeholder(tf.float32)

In [5]:
# weights and bias
W = tf.Variable(tf.random_normal([3,1], name='weight'))
b = tf.Variable(tf.random_normal([1], name='bias'))

In [6]:
# hypothesis
hypothesis = tf.matmul(X, W) + b

In [7]:
# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# optimize using gradient_descent_algorithm
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# launch session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
# for learning
for step in range(2001) :
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X : x_data, Y : y_data})

    if (step % 10 == 0) :
        print(step, "Cost : ", cost_val, "\nPredicition : \n", hy_val)

0 Cost :  40676.457 
Predicition : 
 [[-22.699747]
 [-33.747646]
 [-29.851011]
 [-32.746254]
 [-27.2615  ]]
10 Cost :  13.709518 
Predicition : 
 [[155.67   ]
 [180.66571]
 [181.40051]
 [197.30264]
 [136.28735]]
20 Cost :  13.267424 
Predicition : 
 [[156.19588]
 [181.32394]
 [182.03548]
 [197.99542]
 [136.79486]]
30 Cost :  13.197977 
Predicition : 
 [[156.1837 ]
 [181.3354 ]
 [182.03322]
 [197.99425]
 [136.80902]]
40 Cost :  13.128845 
Predicition : 
 [[156.16992]
 [181.34488]
 [182.02902]
 [197.99095]
 [136.82166]]
50 Cost :  13.060167 
Predicition : 
 [[156.15619]
 [181.35432]
 [182.02484]
 [197.9877 ]
 [136.83424]]
60 Cost :  12.991812 
Predicition : 
 [[156.14249]
 [181.36374]
 [182.02069]
 [197.98444]
 [136.84682]]
70 Cost :  12.923845 
Predicition : 
 [[156.12881]
 [181.37312]
 [182.01653]
 [197.9812 ]
 [136.85934]]
80 Cost :  12.85623 
Predicition : 
 [[156.11519]
 [181.38249]
 [182.01239]
 [197.97795]
 [136.87184]]
90 Cost :  12.788954 
Predicition : 
 [[156.10161]
 [181.3918

890 Cost :  8.433871 
Predicition : 
 [[155.12637]
 [182.06235]
 [181.71191]
 [197.74103]
 [137.78058]]
900 Cost :  8.390462 
Predicition : 
 [[155.1155 ]
 [182.06985]
 [181.7086 ]
 [197.7384 ]
 [137.79062]]
910 Cost :  8.34732 
Predicition : 
 [[155.10463]
 [182.07732]
 [181.7053 ]
 [197.73576]
 [137.80061]]
920 Cost :  8.304422 
Predicition : 
 [[155.0938 ]
 [182.08476]
 [181.70201]
 [197.73315]
 [137.81058]]
930 Cost :  8.261702 
Predicition : 
 [[155.08298]
 [182.0922 ]
 [181.69873]
 [197.73053]
 [137.82053]]
940 Cost :  8.219235 
Predicition : 
 [[155.0722 ]
 [182.0996 ]
 [181.69545]
 [197.72794]
 [137.83046]]
950 Cost :  8.177025 
Predicition : 
 [[155.06146]
 [182.10698]
 [181.6922 ]
 [197.72533]
 [137.84035]]
960 Cost :  8.134976 
Predicition : 
 [[155.05075]
 [182.11436]
 [181.68895]
 [197.72273]
 [137.85023]]
970 Cost :  8.093218 
Predicition : 
 [[155.04007]
 [182.1217 ]
 [181.6857 ]
 [197.72015]
 [137.86008]]
980 Cost :  8.051664 
Predicition : 
 [[155.02942]
 [182.12904]
 

1860 Cost :  5.149203 
Predicition : 
 [[154.19724]
 [182.70163]
 [181.43013]
 [197.5143 ]
 [138.63885]]
1870 Cost :  5.1235127 
Predicition : 
 [[154.18889]
 [182.70738]
 [181.42761]
 [197.51225]
 [138.6466 ]]
1880 Cost :  5.0979424 
Predicition : 
 [[154.18056]
 [182.71312]
 [181.42508]
 [197.5102 ]
 [138.65433]]
1890 Cost :  5.0725794 
Predicition : 
 [[154.17226]
 [182.71881]
 [181.42256]
 [197.50813]
 [138.662  ]]
1900 Cost :  5.047278 
Predicition : 
 [[154.16399]
 [182.72453]
 [181.42007]
 [197.5061 ]
 [138.66971]]
1910 Cost :  5.022109 
Predicition : 
 [[154.1557 ]
 [182.73021]
 [181.41756]
 [197.50403]
 [138.67735]]
1920 Cost :  4.997093 
Predicition : 
 [[154.14746]
 [182.73589]
 [181.41507]
 [197.502  ]
 [138.685  ]]
1930 Cost :  4.9722137 
Predicition : 
 [[154.13925]
 [182.74155]
 [181.41258]
 [197.49998]
 [138.69263]]
1940 Cost :  4.947459 
Predicition : 
 [[154.13106]
 [182.7472 ]
 [181.4101 ]
 [197.49796]
 [138.70023]]
1950 Cost :  4.9228945 
Predicition : 
 [[154.1229 